import {
  BlinkingNerdSpinner,
  SpinnerManager,
  type BlinkingNerdSpinnerTheme,
  type Spinner,
  type SpinnerNotification,
} from "./spinner.ts"

type StatusListener = (label: string | null) => void

export interface StatusSpinnerTheme extends BlinkingNerdSpinnerTheme {
  accent?: (text: string) => string
}

/**
 * Direction of the bytes currently moving on the status row.
 *
 * - `"up"` — request body is being uploaded.
 * - `"down"` — response stream is being received.
 * - `"idle"` — neither (e.g. waiting on TTFB, or a tool is running locally).
 */
export type StatusDirection = "up" | "down" | "idle"

/**
 * Lifecycle phase of the current status entry. Renderers use this to pick
 * the leftmost glyph, the directional arrow, and the foreground color of
 * the byte counter without re-parsing the label string.
 *
 * Mapping to today's labels (see `src/client.ts` and `src/agent.ts`):
 *
 * - `"connect"` — TCP/TLS handshake before any body is written
 * - `"upload"` — POST body in flight (`"Sending request"`)
 * - `"wait-headers"` — body fully sent, waiting on TTFB (`"Waiting for response"`)
 * - `"stream"` — first SSE event arrived but no `content_block_start` yet
 * - `"thinking"` — current SSE block is a `thinking` block
 * - `"writing"` — current SSE block is a `text` block (the visible response)
 * - `"tool-input"` — current SSE block is a `tool_use` block, JSON streaming
 * - `"tool-dispatch"` — tool_use SSE block closed, agent about to invoke tool
 * - `"tool-run"` — local tool executor is running (`"Running <name>"`)
 * - `"auth-refresh"` — 401 retry path, oauth refresh in flight
 * - `"error"` — failed request (non-2xx after retries)
 * - `"aborted"` — user cancelled (Ctrl+C / Esc) mid-turn
 * - `"done"` — terminal state; status will clear shortly
 */
export type StatusPhase =
  | "connect"
  | "upload"
  | "wait-headers"
  | "stream"
  | "thinking"
  | "writing"
  | "tool-input"
  | "tool-dispatch"
  | "tool-run"
  | "auth-refresh"
  | "error"
  | "aborted"
  | "done"

/**
 * What we're talking to. All fields optional; renderers compose a "to
 * whom" subtitle from whichever are present.
 */
export interface StatusActivityTarget {
  /** Hostname only, no scheme. e.g. `"api.anthropic.com"`. */
  host?: string
  /** Wire protocol from `NetworkResponse.transport.protocol`. `"h2"` etc. */
  protocol?: string
  /** Resolved model id, e.g. `"claude-opus-4-7[1m]"`. */
  model?: string
}

/**
 * Structured "what is moving right now" payload.
 *
 * All fields are optional. The status renderer composes the row from
 * whichever fields are present and degrades gracefully at narrow widths.
 * The label string on `StatusEntry` remains the human-readable fallback
 * for renderers that don't know about activity (e.g. line-mode
 * {@link StatusRenderer}).
 *
 * Merge semantics: passing `activity` to {@link StatusHandle.update} or
 * {@link StatusHandle.updateActivity} merges fields onto the entry's
 * existing activity (a defined value overwrites, `undefined` leaves the
 * prior value alone). `target` merges sub-object-style. To "reset" the
 * activity, use a terminal `phase` ("done"/"aborted"/"error") so the
 * renderer can interpret intent — there is no explicit clear-activity
 * operation. Calling `clear()` removes the entry entirely.
 */
export interface StatusActivity {
  direction?: StatusDirection
  phase?: StatusPhase
  /** Bytes sent on the request body so far. */
  sentBytes?: number
  /** Bytes received on the response body so far. */
  recvBytes?: number
  /** Context-window footprint of the request (input + cache_read + cache_create). */
  sentTokens?: number
  /** Output tokens generated by the response so far. */
  recvTokens?: number
  target?: StatusActivityTarget
  /** ms timestamp (`Date.now()`) of the entry's start. Renderer derives elapsed. */
  startedAt?: number
  /** Tool name when `phase` is one of the `"tool-*"` values. */
  toolName?: string
  /** Short one-line hint extracted from tool input (e.g. `"cd /tmp && ls"`). */
  hint?: string
}

export interface StatusMetadata {
  notificationId?: string
  category?: string
  spinnerTheme?: StatusSpinnerTheme
  /**
   * Structured network/tool activity payload. When present, fields are
   * merged onto the entry's existing activity (defined values overwrite,
   * undefined fields are left as-is). `target` merges sub-object-style.
   */
  activity?: StatusActivity
}

export interface StatusHandle {
  update(label: string, metadata?: StatusMetadata): void
  /**
   * Merge an activity partial onto the entry without touching the label.
   * Lower-friction than calling `update(label, {activity})` when only
   * byte counters or rate metrics changed.
   */
  updateActivity(partial: StatusActivity): void
  clear(): void
}

type StatusEntry = {
  id: number
  label: string
  notificationId?: string
  category?: string
  spinnerTheme?: StatusSpinnerTheme
  activity?: StatusActivity
}

export interface StatusSnapshot {
  label: string
  notificationId?: string
  category?: string
  spinnerTheme?: StatusSpinnerTheme
  activity?: StatusActivity
}

function dim(text: string): string {
  return `\x1b[2m${text}\x1b[22m`
}

/**
 * Merge a {@link StatusActivity} partial onto an entry's existing
 * activity. Fields that are `undefined` on the partial leave the prior
 * value untouched. `target` merges sub-object-style. See
 * {@link StatusActivity} for the semantics.
 */
function applyActivity(entry: StatusEntry, partial: StatusActivity): void {
  const a = entry.activity ?? (entry.activity = {})
  if (partial.direction !== undefined) a.direction = partial.direction
  if (partial.phase !== undefined) a.phase = partial.phase
  if (partial.sentBytes !== undefined) a.sentBytes = partial.sentBytes
  if (partial.recvBytes !== undefined) a.recvBytes = partial.recvBytes
  if (partial.sentTokens !== undefined) a.sentTokens = partial.sentTokens
  if (partial.recvTokens !== undefined) a.recvTokens = partial.recvTokens
  if (partial.startedAt !== undefined) a.startedAt = partial.startedAt
  if (partial.toolName !== undefined) a.toolName = partial.toolName
  if (partial.hint !== undefined) a.hint = partial.hint
  if (partial.target) {
    a.target = { ...(a.target ?? {}), ...partial.target }
  }
}

function applyMetadata(entry: StatusEntry, metadata?: StatusMetadata): void {
  if (!metadata) return
  if ("notificationId" in metadata) {
    entry.notificationId = metadata.notificationId
  }
  if ("category" in metadata) {
    entry.category = metadata.category
  }
  if ("spinnerTheme" in metadata) {
    entry.spinnerTheme = metadata.spinnerTheme
  }
  if (metadata.activity) {
    applyActivity(entry, metadata.activity)
  }
}

export class StatusBus {
  private listeners = new Set<StatusListener>()
  private entries: StatusEntry[] = []
  private nextId = 1

  subscribe(listener: StatusListener): () => void {
    this.listeners.add(listener)
    listener(this.current())
    return () => {
      this.listeners.delete(listener)
    }
  }

  create(label: string, metadata?: StatusMetadata): StatusHandle {
    const id = this.nextId++
    const entry: StatusEntry = { id, label }
    applyMetadata(entry, metadata)
    this.entries.push(entry)
    this.emit()

    return {
      update: (nextLabel: string, nextMetadata?: StatusMetadata) => {
        const currentEntry = this.entries.find((item) => item.id === id)
        if (!currentEntry) return
        currentEntry.label = nextLabel
        applyMetadata(currentEntry, nextMetadata)
        this.emit()
      },
      updateActivity: (partial: StatusActivity) => {
        const currentEntry = this.entries.find((item) => item.id === id)
        if (!currentEntry) return
        applyActivity(currentEntry, partial)
        this.emit()
      },
      clear: () => {
        this.entries = this.entries.filter((item) => item.id !== id)
        this.emit()
      },
    }
  }

  current(): string | null {
    return this.entries.length > 0 ? this.entries[this.entries.length - 1].label : null
  }

  currentStatus(): StatusSnapshot | null {
    const entry = this.entries.length > 0 ? this.entries[this.entries.length - 1] : null
    if (!entry) return null
    return {
      label: entry.label,
      notificationId: entry.notificationId,
      category: entry.category,
      spinnerTheme: entry.spinnerTheme,
      activity: entry.activity ? { ...entry.activity } : undefined,
    }
  }

  reset(): void {
    this.entries = []
    this.emit()
  }

  private emit(): void {
    const current = this.current()
    for (const listener of this.listeners) {
      listener(current)
    }
  }
}

type StatusOutput = Pick<NodeJS.WriteStream, "write"> & {
  isTTY?: boolean
}

export interface StatusRendererOptions {
  maxFps?: number
  spinner?: Spinner<StatusSpinnerTheme>
  spinnerTheme?: StatusSpinnerTheme
  spinnerSwitchGraceMs?: number
  now?: () => number
}

export class StatusRenderer {
  private readonly bus: StatusBus
  private readonly output: StatusOutput
  private readonly maxFps: number
  private readonly spinnerManager: SpinnerManager<StatusSpinnerTheme>
  private readonly gap = " "
  private baseSpinnerTheme: StatusSpinnerTheme
  private unsubscribe: (() => void) | null = null
  private timer: ReturnType<typeof setTimeout> | null = null
  private label: string | null = null
  private spinnerGlyph = ""
  private visible = false
  private suspended = false

  constructor(
    bus: StatusBus,
    output: StatusOutput = process.stdout,
    intervalMsOrOptions: number | StatusRendererOptions = 80,
  ) {
    this.bus = bus
    this.output = output
    const normalized =
      typeof intervalMsOrOptions === "number"
        ? {
            maxFps: intervalMsOrOptions <= 0 ? 0 : 1000 / intervalMsOrOptions,
          }
        : intervalMsOrOptions

    this.maxFps = normalized.maxFps ?? 12.5
    this.baseSpinnerTheme = normalized.spinnerTheme ?? {}
    this.spinnerManager = new SpinnerManager<StatusSpinnerTheme>({
      spinner: normalized.spinner ?? new BlinkingNerdSpinner(),
      theme: this.baseSpinnerTheme,
      notification: {},
      maxSwitchGraceMs: normalized.spinnerSwitchGraceMs,
      now: normalized.now,
    })
  }

  start(): void {
    if (this.unsubscribe || this.output.isTTY === false) return
    this.unsubscribe = this.bus.subscribe(() => {
      this.onBusUpdate()
    })
  }

  stop(): void {
    this.stopTimer()
    if (this.unsubscribe) {
      this.unsubscribe()
      this.unsubscribe = null
    }
    this.spinnerManager.unmount()
    this.clearLine()
  }

  suspend(): void {
    if (this.suspended) return
    this.suspended = true
    this.clearLine()
  }

  resume(): void {
    if (!this.suspended) return
    this.suspended = false
    if (this.label) {
      this.spinnerGlyph = this.nextSpinnerGlyph()
      this.renderLine()
    }
  }

  setSpinner(spinner: Spinner<StatusSpinnerTheme>, maxGraceMs?: number): void {
    this.spinnerManager.setSpinner(spinner, maxGraceMs)
    if (this.label) {
      this.spinnerGlyph = this.nextSpinnerGlyph()
      if (!this.suspended) this.renderLine()
      this.scheduleNextTick()
    }
  }

  setSpinnerTheme(theme: StatusSpinnerTheme): void {
    this.baseSpinnerTheme = theme
    const active = this.bus.currentStatus()
    if (active?.spinnerTheme) return
    this.spinnerManager.setTheme(theme)
    if (this.label) {
      this.spinnerGlyph = this.nextSpinnerGlyph()
      if (!this.suspended) this.renderLine()
    }
  }

  private onBusUpdate(): void {
    const status = this.bus.currentStatus()
    this.label = status?.label ?? null
    if (!status) {
      this.spinnerManager.unmount()
      this.stopTimer()
      if (!this.suspended) this.clearLine()
      return
    }

    this.spinnerManager.ensureMounted()
    this.spinnerManager.setNotification(this.toNotification(status))
    this.spinnerManager.setTheme(status.spinnerTheme ?? this.baseSpinnerTheme)
    this.spinnerGlyph = this.nextSpinnerGlyph()
    if (!this.suspended) this.renderLine()
    this.scheduleNextTick()
  }

  private toNotification(status: StatusSnapshot): SpinnerNotification {
    return {
      notificationId: status.notificationId,
      category: status.category,
    }
  }

  private scheduleNextTick(): void {
    if (this.timer || !this.label || this.maxFps <= 0) return
    const effectiveFps = this.spinnerManager.effectiveFps(this.maxFps) ?? this.maxFps
    const delayMs = Math.max(16, Math.round(1000 / effectiveFps))
    this.timer = setTimeout(() => {
      this.timer = null
      if (!this.label) return
      this.spinnerGlyph = this.nextSpinnerGlyph()
      if (!this.suspended) this.renderLine()
      this.scheduleNextTick()
    }, delayMs)
  }

  private stopTimer(): void {
    if (!this.timer) return
    clearTimeout(this.timer)
    this.timer = null
  }

  private nextSpinnerGlyph(): string {
    return this.spinnerManager.render(this.maxFps)?.glyph ?? ""
  }

  private renderLine(): void {
    if (!this.label) return
    const prefix = this.spinnerGlyph ? `${this.spinnerGlyph}${this.gap}` : ""
    this.output.write(`\r\x1b[2K${prefix}${dim(this.label)}`)
    this.visible = true
  }

  private clearLine(): void {
    if (!this.visible) return
    this.output.write("\r\x1b[2K")
    this.visible = false
  }
}

export const GLOBAL_STATUS_BUS = new StatusBus()
