import {
  BlinkingNerdSpinner,
  SpinnerManager,
  type BlinkingNerdSpinnerTheme,
  type Spinner,
  type SpinnerNotification,
} from "./spinner.ts"
import { displayWidth } from "./term-width.ts"

type StatusListener = (label: string | null) => void

export interface StatusSpinnerTheme extends BlinkingNerdSpinnerTheme {
  accent?: (text: string) => string
}

/**
 * Direction of the bytes currently moving on the status row.
 *
 * - `"up"` — request body is being uploaded.
 * - `"down"` — response stream is being received.
 * - `"idle"` — neither (e.g. waiting on TTFB, or a tool is running locally).
 */
export type StatusDirection = "up" | "down" | "idle"

/**
 * Lifecycle phase of the current status entry. Renderers use this to pick
 * the leftmost glyph, the directional arrow, and the foreground color of
 * the byte counter without re-parsing the label string.
 *
 * Mapping to today's labels (see `src/client.ts` and `src/agent.ts`):
 *
 * - `"connect"` — TCP/TLS handshake before any body is written
 * - `"upload"` — POST body in flight (`"Sending request"`)
 * - `"wait-headers"` — body fully sent, waiting on TTFB (`"Waiting for response"`)
 * - `"stream"` — first SSE event arrived but no `content_block_start` yet
 * - `"thinking"` — current SSE block is a `thinking` block
 * - `"writing"` — current SSE block is a `text` block (the visible response)
 * - `"tool-input"` — current SSE block is a `tool_use` block, JSON streaming
 * - `"tool-dispatch"` — tool_use SSE block closed, agent about to invoke tool
 * - `"tool-run"` — local tool executor is running (`"Running <name>"`)
 * - `"auth-refresh"` — 401 retry path, oauth refresh in flight
 * - `"error"` — failed request (non-2xx after retries)
 * - `"aborted"` — user cancelled (Ctrl+C / Esc) mid-turn
 * - `"done"` — terminal state; status will clear shortly
 */
export type StatusPhase =
  | "connect"
  | "upload"
  | "wait-headers"
  | "stream"
  | "thinking"
  | "writing"
  | "tool-input"
  | "tool-dispatch"
  | "tool-run"
  | "auth-refresh"
  | "error"
  | "aborted"
  | "done"

/**
 * What we're talking to. All fields optional; renderers compose a "to
 * whom" subtitle from whichever are present.
 */
export interface StatusActivityTarget {
  /** Hostname only, no scheme. e.g. `"api.anthropic.com"`. */
  host?: string
  /** Wire protocol from `NetworkResponse.transport.protocol`. `"h2"` etc. */
  protocol?: string
  /** Resolved model id, e.g. `"claude-opus-4-7[1m]"`. */
  model?: string
}

/**
 * Structured "what is moving right now" payload.
 *
 * All fields are optional. The status renderer composes the row from
 * whichever fields are present and degrades gracefully at narrow widths.
 * The label string on `StatusEntry` remains the human-readable fallback
 * for renderers that don't know about activity (e.g. line-mode
 * {@link StatusRenderer}).
 *
 * Merge semantics: passing `activity` to {@link StatusHandle.update} or
 * {@link StatusHandle.updateActivity} merges fields onto the entry's
 * existing activity (a defined value overwrites, `undefined` leaves the
 * prior value alone). `target` merges sub-object-style. To "reset" the
 * activity, use a terminal `phase` ("done"/"aborted"/"error") so the
 * renderer can interpret intent — there is no explicit clear-activity
 * operation. Calling `clear()` removes the entry entirely.
 */
export interface StatusActivity {
  direction?: StatusDirection
  phase?: StatusPhase
  /** Bytes sent on the request body so far. */
  sentBytes?: number
  /** Bytes received on the response body so far. */
  recvBytes?: number
  /** Context-window footprint of the request (input + cache_read + cache_create). */
  sentTokens?: number
  /** Output tokens generated by the response so far. */
  recvTokens?: number
  target?: StatusActivityTarget
  /** ms timestamp (`Date.now()`) of the entry's start. Renderer derives elapsed. */
  startedAt?: number
  /**
   * ms timestamp (`Date.now()`) of the most recent chunk arrival. The renderer
   * uses this to detect the "no bytes for >N seconds" stalled state, which is
   * the answer to "why is `Calling Write: streaming input (10 B) (30s)`
   * frozen?" — the model went quiet mid-stream but the elapsed clock keeps
   * ticking on its own timer. When `lastChunkAt` exists AND
   * `now - lastChunkAt > STALL_THRESHOLD_MS`, the row flips to the amber
   * `⋯ stalled · last byte Ns ago` form so the user can tell the difference
   * between "still receiving slowly" and "actually hung".
   */
  lastChunkAt?: number
  /** Tool name when `phase` is one of the `"tool-*"` values. */
  toolName?: string
  /** Short one-line hint extracted from tool input (e.g. `"cd /tmp && ls"`). */
  hint?: string
}

export interface StatusMetadata {
  notificationId?: string
  category?: string
  spinnerTheme?: StatusSpinnerTheme
  /**
   * Structured network/tool activity payload. When present, fields are
   * merged onto the entry's existing activity (defined values overwrite,
   * undefined fields are left as-is). `target` merges sub-object-style.
   */
  activity?: StatusActivity
}

export interface StatusHandle {
  update(label: string, metadata?: StatusMetadata): void
  /**
   * Merge an activity partial onto the entry without touching the label.
   * Lower-friction than calling `update(label, {activity})` when only
   * byte counters or rate metrics changed.
   */
  updateActivity(partial: StatusActivity): void
  clear(): void
}

type StatusEntry = {
  id: number
  label: string
  notificationId?: string
  category?: string
  spinnerTheme?: StatusSpinnerTheme
  activity?: StatusActivity
}

export interface StatusSnapshot {
  /**
   * Stable identity of the underlying entry. Increments on every
   * `StatusBus.create()`. Renderers use this to detect "new entry"
   * vs "label updated on same entry" -- needed for the per-status
   * elapsed timer, which must reset on (new tool / new request)
   * but persist across phase transitions on the same handle.
   */
  id: number
  label: string
  notificationId?: string
  category?: string
  spinnerTheme?: StatusSpinnerTheme
  activity?: StatusActivity
}

function dim(text: string): string {
  return `\x1b[2m${text}\x1b[22m`
}

/**
 * Compact "wall-clock elapsed" formatter for status-row suffixes.
 *
 * Ladder:
 *   - `< 60s`              -> `"<n>s"`              (e.g. `"2s"`)
 *   - `60s..3599s`         -> `"<m>m <s>s"`         (e.g. `"1m 2s"`)
 *   - `>= 3600s`           -> `"<h>h <m>m"`         (e.g. `"1h 2m"` -- seconds dropped at hour scale)
 *
 * Negative inputs and `NaN` are clamped to `0` (returns `"0s"`).
 */
export function formatElapsed(ms: number): string {
  const safe = Number.isFinite(ms) && ms > 0 ? ms : 0
  const totalSec = Math.floor(safe / 1000)
  if (totalSec < 60) return `${totalSec}s`
  const totalMin = Math.floor(totalSec / 60)
  const sec = totalSec - totalMin * 60
  if (totalMin < 60) return `${totalMin}m ${sec}s`
  const hours = Math.floor(totalMin / 60)
  const min = totalMin - hours * 60
  return `${hours}h ${min}m`
}

/**
 * Returns a renderable "elapsed" suffix for a status row, already
 * wrapped in faint SGR codes (so the parens + digits visually fade
 * relative to the label).
 *
 * Suppressed under 1 second to avoid flicker on fast operations that
 * complete in <1s (the row would briefly flash `(0s)` and then clear).
 *
 * Includes the LEADING space, so callers concatenate
 * unconditionally: `${label}${formatElapsedSuffix(ms)}` produces
 * either `"Thinking"` or `"Thinking <faint>(2s)</faint>"`.
 */
export function formatElapsedSuffix(ms: number): string {
  if (!Number.isFinite(ms) || ms < 1000) return ""
  return ` ${dim(`(${formatElapsed(ms)})`)}`
}

// ---------------------------------------------------------------------------
// Activity infix
//
// Renders the structured StatusActivity payload (bytes / tokens / direction /
// host / lastChunkAt) as a compact infix between the label and the elapsed
// suffix. Without this, the rich data populated by `NetworkActivityObserver`
// is silently discarded: renderers only ever painted `{glyph} {label}` and
// the user had no way to tell "model is streaming slowly" from "frozen, no
// bytes for 30s". See docs/changes/2026-05-17-feat-live-activity-row.md.
// ---------------------------------------------------------------------------

/**
 * Time without a chunk after which the row flips to the amber "⋯ stalled"
 * form. Picked at 2s as the boundary between "model is generating slowly"
 * (which can take a couple seconds between tokens for deep thinking blocks)
 * and "the wire has gone dead" (which the user needs to know about so they
 * can hit Esc and retry instead of staring at a frozen counter).
 */
export const STALL_THRESHOLD_MS = 2_000

/** Faint white SGR pair for the segment value text. */
function faintWhite(text: string): string {
  return `\x1b[2;37m${text}\x1b[22;39m`
}

/** Internal compact byte formatter — mirrors client.ts and agent.ts copies. */
function fmtBytes(n: number): string {
  if (n < 1024) return `${n} B`
  if (n < 1024 * 1024) return `${(n / 1024).toFixed(1)} KB`
  return `${(n / 1024 / 1024).toFixed(1)} MB`
}

/** Internal compact token formatter — mirrors quota-status/render.ts. */
function fmtTokens(n: number): string {
  if (n >= 1_000_000) return `${(n / 1_000_000).toFixed(1).replace(/\.0$/, "")}M`
  if (n >= 1_000) return `${(n / 1_000).toFixed(1).replace(/\.0$/, "")}k`
  return String(n)
}

/**
 * Options for {@link formatActivityInfix}.
 */
export interface FormatActivityOptions {
  /** Wall clock for stall detection + rate calc. Defaults to `Date.now()`. */
  now?: number
  /**
   * Maximum display cells the rendered infix may consume. When set,
   * trailing segments (host, rate, tokens, then bytes) are dropped
   * right-to-left until the result fits. Returns "" if even just the
   * arrow doesn't fit. Unset = no width cap.
   */
  maxWidth?: number
  /** Override the stalled threshold. Defaults to {@link STALL_THRESHOLD_MS}. */
  stallThresholdMs?: number
  /**
   * ms timestamp the status entry was created. Used only for the per-second
   * rate segment (bytes/s when no token signal, tok/s when recvTokens is
   * present). Omit to suppress the rate segment.
   */
  entryStartedAt?: number
  /**
   * When true, suppress the bytes segment. Used by renderers when the label
   * itself already shows a trailing `(N B)` (today's pattern in
   * `client.ts` for tool-input streaming) — otherwise the row would render
   * both `(10 B)` in the label AND `1.2 KB` in the infix, which is
   * actively misleading because the numbers come from different sources
   * (model-emitted JSON length vs. on-the-wire chunk bytes).
   */
  hideBytes?: boolean
}

/**
 * Render the {@link StatusActivity} payload as a compact infix string.
 *
 * Shape (leading space included so callers concatenate unconditionally):
 *
 *     ` {arrow} {bytes} · {tokens} · {rate} · {host}:{proto}`
 *
 * Returns `""` when there's no activity or nothing to show.
 *
 * Arrow semantics:
 *   - `↑` (sky)            — `direction: "up"`, body is uploading
 *   - `↓` (lime)           — `direction: "down"`, chunks arriving
 *   - `·` (dim)            — `direction: "idle"` or unspecified
 *   - `⋯ stalled` (gold)   — `direction: "down"` AND no chunk for
 *                             >`stallThresholdMs` ms
 *
 * Segment drop order under `maxWidth` pressure (right-to-left):
 *   1. host:proto   (lowest priority — context, not progress)
 *   2. rate
 *   3. tokens
 *   4. bytes        (highest priority — the "is it moving" signal)
 */
export function formatActivityInfix(
  activity: StatusActivity | undefined,
  opts: FormatActivityOptions = {},
): string {
  if (!activity) return ""
  const now = opts.now ?? Date.now()
  const stallThresh = opts.stallThresholdMs ?? STALL_THRESHOLD_MS
  const dir = activity.direction
  const stalled =
    dir === "down" && activity.lastChunkAt != null && now - activity.lastChunkAt > stallThresh

  // ---- arrow ----
  // Three colors map to the three useful directional states. The stalled
  // case wins over direction because it's a strictly more important
  // signal — "moving" answers "is something happening", "stalled" answers
  // "is anything happening at all".
  let arrow: string
  if (stalled)
    arrow = `\x1b[38;5;214m⋯ stalled\x1b[39m` // gold
  else if (dir === "up")
    arrow = `\x1b[38;5;45m↑\x1b[39m` // sky
  else if (dir === "down")
    arrow = `\x1b[38;5;118m↓\x1b[39m` // lime
  else arrow = `\x1b[2m·\x1b[22m` // dim

  // ---- segments (left-to-right priority) ----
  const segs: string[] = []

  // Bytes (highest priority — answers "how much").
  if (!opts.hideBytes) {
    const b = pickBytesForDirection(activity)
    if (b != null && b > 0) segs.push(faintWhite(fmtBytes(b)))
  }

  // Tokens (model-side counter — only available when caller estimates).
  const tok = dir === "up" ? activity.sentTokens : activity.recvTokens
  if (tok != null && tok > 0) {
    // The `~` prefix is load-bearing UX: any non-final value is an
    // estimate (chars/3.5 heuristic), and we don't want to imply it's the
    // billed count. Final `output_tokens` from the server can be plugged
    // in by the caller without the `~` (we just render whatever number
    // the caller supplied — the `~` is unconditional today).
    segs.push(faintWhite(`~${fmtTokens(tok)} tok`))
  }

  // Rate (computed against entry-start time, which the renderer owns —
  // skipped if no startedAt or if elapsed < 500ms so the number doesn't
  // jitter wildly on the first few hundred ms of a request).
  if (opts.entryStartedAt != null && opts.entryStartedAt > 0) {
    const elapsedMs = now - opts.entryStartedAt
    if (elapsedMs >= 500) {
      const rate = computeRate(activity, elapsedMs, dir)
      if (rate) segs.push(dim(rate))
    }
  }

  // Target host/proto (lowest priority — context, drops first).
  const target = activity.target
  if (target?.host) {
    const proto = target.protocol ? `:${target.protocol}` : ""
    segs.push(faintWhite(`${target.host}${proto}`))
  }

  // Stalled gets an extra "last byte Ns ago" segment FIRST in the segs
  // list (most relevant info first). Pre-prepended so it survives
  // right-to-left dropping below.
  if (stalled && activity.lastChunkAt != null) {
    const sinceMs = now - activity.lastChunkAt
    const sinceS = Math.max(1, Math.floor(sinceMs / 1000))
    segs.unshift(faintWhite(`last byte ${sinceS}s ago`))
  }

  // ---- composition + width-aware degradation ----
  // For the stalled case the arrow is a two-word phrase (`⋯ stalled`),
  // so we use a `·` between the arrow and the first segment instead of
  // a bare space — otherwise `⋯ stalled last byte 5s ago` reads as one
  // run-on phrase. For the single-glyph arrows (↑/↓/·) the existing
  // single-space gap is cleaner.
  const sep = dim(" · ")
  const arrowGap = stalled && segs.length > 0 ? sep : " "
  const compose = (parts: string[]): string =>
    parts.length === 0 ? ` ${arrow}` : ` ${arrow}${arrowGap}${parts.join(sep)}`
  let result = compose(segs)

  if (opts.maxWidth != null && Number.isFinite(opts.maxWidth)) {
    while (displayWidth(result) > opts.maxWidth && segs.length > 0) {
      segs.pop()
      result = compose(segs)
    }
    if (displayWidth(result) > opts.maxWidth) return ""
  }
  return result
}

/**
 * Pick the bytes counter that matches the current direction. Falls back to
 * whichever counter is populated so a tracker that misses a `direction`
 * update doesn't silently lose its number.
 */
function pickBytesForDirection(activity: StatusActivity): number | undefined {
  if (activity.direction === "up") return activity.sentBytes ?? activity.recvBytes
  if (activity.direction === "down") return activity.recvBytes ?? activity.sentBytes
  // idle / unspecified: prefer whichever moved last (recvBytes wins because
  // most of our lifecycle is "receiving stream").
  return activity.recvBytes ?? activity.sentBytes
}

/**
 * Compute a per-second rate string. Prefers tok/s when tokens are
 * available (more meaningful for "streaming text"), falls back to bytes/s.
 * Returns null when nothing useful can be computed.
 */
function computeRate(
  activity: StatusActivity,
  elapsedMs: number,
  dir: StatusDirection | undefined,
): string | null {
  const secs = elapsedMs / 1000
  if (secs <= 0) return null
  const tok = dir === "up" ? activity.sentTokens : activity.recvTokens
  if (tok != null && tok > 0) {
    const tps = tok / secs
    if (tps < 10) return `${tps.toFixed(1)} tok/s`
    return `${Math.round(tps)} tok/s`
  }
  const b = pickBytesForDirection(activity)
  if (b != null && b > 0) {
    const bps = b / secs
    if (bps < 1024) return `${Math.round(bps)} B/s`
    return `${(bps / 1024).toFixed(1)} KB/s`
  }
  return null
}

/**
 * Merge a {@link StatusActivity} partial onto an entry's existing
 * activity. Fields that are `undefined` on the partial leave the prior
 * value untouched. `target` merges sub-object-style. See
 * {@link StatusActivity} for the semantics.
 */
function applyActivity(entry: StatusEntry, partial: StatusActivity): void {
  const a = entry.activity ?? (entry.activity = {})
  if (partial.direction !== undefined) a.direction = partial.direction
  if (partial.phase !== undefined) a.phase = partial.phase
  if (partial.sentBytes !== undefined) a.sentBytes = partial.sentBytes
  if (partial.recvBytes !== undefined) a.recvBytes = partial.recvBytes
  if (partial.sentTokens !== undefined) a.sentTokens = partial.sentTokens
  if (partial.recvTokens !== undefined) a.recvTokens = partial.recvTokens
  if (partial.startedAt !== undefined) a.startedAt = partial.startedAt
  if (partial.lastChunkAt !== undefined) a.lastChunkAt = partial.lastChunkAt
  if (partial.toolName !== undefined) a.toolName = partial.toolName
  if (partial.hint !== undefined) a.hint = partial.hint
  if (partial.target) {
    a.target = { ...(a.target ?? {}), ...partial.target }
  }
}

function applyMetadata(entry: StatusEntry, metadata?: StatusMetadata): void {
  if (!metadata) return
  if ("notificationId" in metadata) {
    entry.notificationId = metadata.notificationId
  }
  if ("category" in metadata) {
    entry.category = metadata.category
  }
  if ("spinnerTheme" in metadata) {
    entry.spinnerTheme = metadata.spinnerTheme
  }
  if (metadata.activity) {
    applyActivity(entry, metadata.activity)
  }
}

export class StatusBus {
  private listeners = new Set<StatusListener>()
  private entries: StatusEntry[] = []
  private nextId = 1

  subscribe(listener: StatusListener): () => void {
    this.listeners.add(listener)
    listener(this.current())
    return () => {
      this.listeners.delete(listener)
    }
  }

  create(label: string, metadata?: StatusMetadata): StatusHandle {
    const id = this.nextId++
    const entry: StatusEntry = { id, label }
    applyMetadata(entry, metadata)
    this.entries.push(entry)
    this.emit()

    return {
      update: (nextLabel: string, nextMetadata?: StatusMetadata) => {
        const currentEntry = this.entries.find((item) => item.id === id)
        if (!currentEntry) return
        currentEntry.label = nextLabel
        applyMetadata(currentEntry, nextMetadata)
        this.emit()
      },
      updateActivity: (partial: StatusActivity) => {
        const currentEntry = this.entries.find((item) => item.id === id)
        if (!currentEntry) return
        applyActivity(currentEntry, partial)
        this.emit()
      },
      clear: () => {
        this.entries = this.entries.filter((item) => item.id !== id)
        this.emit()
      },
    }
  }

  current(): string | null {
    return this.entries.length > 0 ? this.entries[this.entries.length - 1].label : null
  }

  currentStatus(): StatusSnapshot | null {
    const entry = this.entries.length > 0 ? this.entries[this.entries.length - 1] : null
    if (!entry) return null
    return {
      id: entry.id,
      label: entry.label,
      notificationId: entry.notificationId,
      category: entry.category,
      spinnerTheme: entry.spinnerTheme,
      activity: entry.activity ? { ...entry.activity } : undefined,
    }
  }

  reset(): void {
    this.entries = []
    this.emit()
  }

  private emit(): void {
    const current = this.current()
    for (const listener of this.listeners) {
      listener(current)
    }
  }
}

type StatusOutput = Pick<NodeJS.WriteStream, "write"> & {
  isTTY?: boolean
}

/**
 * Trailing-parens byte-count detector, shared with `LiveAreaStatusController`.
 * Matches `(10 B)`, `(2.0 KB)`, `(1.5 MB)`. Used by the renderer to suppress
 * the activity infix's bytes segment when the label already shows bytes
 * (today's `Calling Write: streaming input (10 B)` pattern from client.ts).
 */
const LABEL_BYTES_RE = /\(\d+(?:\.\d+)?\s?(?:B|KB|MB)\)\s*$/

export interface StatusRendererOptions {
  maxFps?: number
  spinner?: Spinner<StatusSpinnerTheme>
  spinnerTheme?: StatusSpinnerTheme
  spinnerSwitchGraceMs?: number
  now?: () => number
}

export class StatusRenderer {
  private readonly bus: StatusBus
  private readonly output: StatusOutput
  private readonly maxFps: number
  private readonly spinnerManager: SpinnerManager<StatusSpinnerTheme>
  private readonly now: () => number
  private readonly gap = " "
  private baseSpinnerTheme: StatusSpinnerTheme
  private unsubscribe: (() => void) | null = null
  private timer: ReturnType<typeof setTimeout> | null = null
  private label: string | null = null
  private spinnerGlyph = ""
  private visible = false
  private suspended = false
  /** See LiveAreaStatusController for the reset-on-id-change rationale. */
  private statusId: number | null = null
  private statusStartedAt = 0

  constructor(
    bus: StatusBus,
    output: StatusOutput = process.stdout,
    intervalMsOrOptions: number | StatusRendererOptions = 80,
  ) {
    this.bus = bus
    this.output = output
    const normalized =
      typeof intervalMsOrOptions === "number"
        ? {
            maxFps: intervalMsOrOptions <= 0 ? 0 : 1000 / intervalMsOrOptions,
          }
        : intervalMsOrOptions

    this.maxFps = normalized.maxFps ?? 12.5
    this.baseSpinnerTheme = normalized.spinnerTheme ?? {}
    this.now = normalized.now ?? (() => Date.now())
    this.spinnerManager = new SpinnerManager<StatusSpinnerTheme>({
      spinner: normalized.spinner ?? new BlinkingNerdSpinner(),
      theme: this.baseSpinnerTheme,
      notification: {},
      maxSwitchGraceMs: normalized.spinnerSwitchGraceMs,
      now: normalized.now,
    })
  }

  start(): void {
    if (this.unsubscribe || this.output.isTTY === false) return
    this.unsubscribe = this.bus.subscribe(() => {
      this.onBusUpdate()
    })
  }

  stop(): void {
    this.stopTimer()
    if (this.unsubscribe) {
      this.unsubscribe()
      this.unsubscribe = null
    }
    this.spinnerManager.unmount()
    this.clearLine()
    this.statusId = null
    this.statusStartedAt = 0
  }

  suspend(): void {
    if (this.suspended) return
    this.suspended = true
    this.clearLine()
  }

  resume(): void {
    if (!this.suspended) return
    this.suspended = false
    if (this.label) {
      this.spinnerGlyph = this.nextSpinnerGlyph()
      this.renderLine()
    }
  }

  setSpinner(spinner: Spinner<StatusSpinnerTheme>, maxGraceMs?: number): void {
    this.spinnerManager.setSpinner(spinner, maxGraceMs)
    if (this.label) {
      this.spinnerGlyph = this.nextSpinnerGlyph()
      if (!this.suspended) this.renderLine()
      this.scheduleNextTick()
    }
  }

  setSpinnerTheme(theme: StatusSpinnerTheme): void {
    this.baseSpinnerTheme = theme
    const active = this.bus.currentStatus()
    if (active?.spinnerTheme) return
    this.spinnerManager.setTheme(theme)
    if (this.label) {
      this.spinnerGlyph = this.nextSpinnerGlyph()
      if (!this.suspended) this.renderLine()
    }
  }

  private onBusUpdate(): void {
    const status = this.bus.currentStatus()
    this.label = status?.label ?? null
    if (!status) {
      this.spinnerManager.unmount()
      this.stopTimer()
      if (!this.suspended) this.clearLine()
      this.statusId = null
      this.statusStartedAt = 0
      return
    }

    // Per-status elapsed timer: reset on entry-identity change (new
    // `create()`), preserve across `update()`s on the same handle.
    // See LiveAreaStatusController.onBusUpdate for the rationale.
    if (status.id !== this.statusId) {
      this.statusId = status.id
      this.statusStartedAt = this.now()
    }

    this.spinnerManager.ensureMounted()
    this.spinnerManager.setNotification(this.toNotification(status))
    this.spinnerManager.setTheme(status.spinnerTheme ?? this.baseSpinnerTheme)
    this.spinnerGlyph = this.nextSpinnerGlyph()
    if (!this.suspended) this.renderLine()
    this.scheduleNextTick()
  }

  private toNotification(status: StatusSnapshot): SpinnerNotification {
    return {
      notificationId: status.notificationId,
      category: status.category,
    }
  }

  private scheduleNextTick(): void {
    if (this.timer || !this.label || this.maxFps <= 0) return
    const effectiveFps = this.spinnerManager.effectiveFps(this.maxFps) ?? this.maxFps
    const delayMs = Math.max(16, Math.round(1000 / effectiveFps))
    this.timer = setTimeout(() => {
      this.timer = null
      if (!this.label) return
      this.spinnerGlyph = this.nextSpinnerGlyph()
      if (!this.suspended) this.renderLine()
      this.scheduleNextTick()
    }, delayMs)
  }

  private stopTimer(): void {
    if (!this.timer) return
    clearTimeout(this.timer)
    this.timer = null
  }

  private nextSpinnerGlyph(): string {
    return this.spinnerManager.render(this.maxFps)?.glyph ?? ""
  }

  private renderLine(): void {
    if (!this.label) return
    const prefix = this.spinnerGlyph ? `${this.spinnerGlyph}${this.gap}` : ""
    // Append the faint elapsed suffix (e.g. " \x1b[2m(2s)\x1b[22m").
    // Empty under 1s. The label is already dim in line-mode so the
    // suffix blends in tonally, but it still gives a wall-clock signal
    // for long-running operations.
    const now = this.now()
    const elapsedMs = this.statusStartedAt > 0 ? now - this.statusStartedAt : 0
    const suffix = formatElapsedSuffix(elapsedMs)
    // Activity infix — bytes/tokens/rate/host between label and elapsed.
    // Same logic as LiveAreaStatusController.paint; see that file for
    // the full rationale (the two renderers stay in step). Empty when
    // no activity is attached, which preserves the legacy "{glyph} {label}
    // (Xs)" line-mode output for callers that don't publish activity.
    const status = this.bus.currentStatus()
    const labelHasBytes = LABEL_BYTES_RE.test(this.label)
    const infix = formatActivityInfix(status?.activity, {
      now,
      entryStartedAt: this.statusStartedAt,
      hideBytes: labelHasBytes,
    })
    this.output.write(`\r\x1b[2K${prefix}${dim(this.label)}${infix}${suffix}`)
    this.visible = true
  }

  private clearLine(): void {
    if (!this.visible) return
    this.output.write("\r\x1b[2K")
    this.visible = false
  }
}

export const GLOBAL_STATUS_BUS = new StatusBus()
